[package]
name = "elitepathfinder"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.5.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
gdk = "0.18.2"
[dependencies.gtk]
package = "gtk4"
version = "0.11.4"
features = ["v4_22"]

[build-dependencies]
glib-build-tools = "0.22.8"
